// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AuthenticateWithTouchID():Promise<boolean>;

export function GetAllCheatSheets():Promise<Array<models.Cheatsheet>>;

export function GetConfig():Promise<models.ConfigResponse>;

export function IsMacOS():Promise<boolean>;
