// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateWithTouchID() {
  return window['go']['main']['App']['AuthenticateWithTouchID']();
}

export function GetBrowsersStats(arg1) {
  return window['go']['main']['App']['GetBrowsersStats'](arg1);
}

export function GetCheatSheets(arg1) {
  return window['go']['main']['App']['GetCheatSheets'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCountriesStats(arg1) {
  return window['go']['main']['App']['GetCountriesStats'](arg1);
}

export function GetDevicesStats(arg1) {
  return window['go']['main']['App']['GetDevicesStats'](arg1);
}

export function GetMetricsOverview(arg1) {
  return window['go']['main']['App']['GetMetricsOverview'](arg1);
}

export function GetOperatingSystemStats(arg1) {
  return window['go']['main']['App']['GetOperatingSystemStats'](arg1);
}

export function GetReferrersStats(arg1) {
  return window['go']['main']['App']['GetReferrersStats'](arg1);
}

export function GetRoutesStats(arg1) {
  return window['go']['main']['App']['GetRoutesStats'](arg1);
}

export function GetStorageUsage() {
  return window['go']['main']['App']['GetStorageUsage']();
}

export function IsMacOS() {
  return window['go']['main']['App']['IsMacOS']();
}

export function UploadCheatsheet(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UploadCheatsheet'](arg1, arg2, arg3, arg4, arg5);
}
