// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { models } from '../models';

export function AuthenticateWithTouchID(): Promise<boolean>;

export function GetBrowsersStats(arg1: string): Promise<models.BrowserStatsResponse>;

export function GetCheatSheets(arg1: models.CheatsheetsConfig): Promise<Array<models.Cheatsheet>>;

export function GetConfig(): Promise<models.ConfigResponse>;

export function GetCountriesStats(arg1: string): Promise<models.CountriesStatsResponse>;

export function GetDevicesStats(arg1: string): Promise<models.DeviceStatsResponse>;

export function GetMetricsOverview(arg1: string): Promise<models.MetricsOverviewResponse>;

export function GetOperatingSystemStats(arg1: string): Promise<models.OperatingSystemStatsResponse>;

export function GetReferrersStats(arg1: string): Promise<models.ReferrerStatsResponse>;

export function GetRoutesStats(arg1: string): Promise<models.RoutesStatsResponse>;

export function GetStorageUsage(): Promise<models.UsageResponse>;

export function IsMacOS(): Promise<boolean>;

export function UploadCheatsheet(
  arg1: string,
  arg2: string,
  arg3: string,
  arg4: string,
  arg5: Array<number>
): Promise<void>;
