// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateWithTouchID() {
  return window['go']['main']['App']['AuthenticateWithTouchID']();
}

export function GetCheatSheets(arg1, arg2) {
  return window['go']['main']['App']['GetCheatSheets'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function IsMacOS() {
  return window['go']['main']['App']['IsMacOS']();
}

export function UploadCheatsheet(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UploadCheatsheet'](arg1, arg2, arg3, arg4, arg5);
}
