// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateWithTouchID() {
  return window['go']['main']['App']['AuthenticateWithTouchID']();
}

export function GetAllCheatSheets() {
  return window['go']['main']['App']['GetAllCheatSheets']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function IsMacOS() {
  return window['go']['main']['App']['IsMacOS']();
}
